# This is a basic workflow to help you get started with Actions

name: CItest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with: # Set the secret as an input
          super_secret: ${{ secrets.SuperSecret }}
        env: # Or as an environment variable
          super_secret: ${{ secrets.SuperSecret }}
          run: echo 'this is' + $super_secret

